services:
  backend:
    build: .
    container_name: backend_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MAIN_DB_URL=jdbc:mysql://db:3306/main_db?useSSL=false&allowPublicKeyRetrieval=true
      - TENANT_DB_BASE_URL=jdbc:mysql://db:3306?useSSL=false&allowPublicKeyRetrieval=true
      - TENANT_DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=main_db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: