-- ========================================
-- Tabela: tb_resource
-- ========================================
CREATE TABLE tb_resource (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    UNIT_VALUE DECIMAL(10,2) NOT NULL,
    CATEGORY ENUM ('COMPONENT','ELECTRICITY','GAS','RAW_MATERIAL','RETAIL','SILICATE','WATER'),
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

ALTER TABLE tb_resource 
    ADD CONSTRAINT UK_AUNVLVM32XB4E6590JC9OOOQ UNIQUE (NAME);

-- ========================================
-- Tabela: tb_batch
-- ========================================
CREATE TABLE tb_batch (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    BATCH_TOTAL_WATER_COST_AT_TIME DECIMAL(10,2) NOT NULL,
    RESOURCE_TOTAL_COST_AT_TIME DECIMAL(10,2) NOT NULL,
    MACHINES_ENERGY_CONSUMPTION_COST_AT_TIME DECIMAL(10,2) NOT NULL,
    BATCH_FINAL_COST_AT_TIME DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

-- ========================================
-- Tabela: tb_resource_transaction
-- ========================================
CREATE TABLE tb_resource_transaction (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    TYPE ENUM ('INCOMING','OUTGOING'),
    RESOURCE_ID BIGINT NOT NULL,
    BATCH_ID BIGINT NULL,
    COST_AT_TIME DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (RESOURCE_ID) REFERENCES tb_resource (ID),
    FOREIGN KEY (BATCH_ID) REFERENCES tb_batch (ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ========================================
-- Tabela: tb_machine
-- ========================================
CREATE TABLE tb_machine (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    POWER DOUBLE NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

-- ========================================
-- Tabela intermediária: tb_batch_resource_usage
-- ========================================
CREATE TABLE tb_batch_resource_usage (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    INITIAL_QUANTITY DOUBLE NOT NULL,
    UMIDITY DOUBLE NOT NULL,
    ADDED_QUANTITY DOUBLE NOT NULL,
    TOTAL_COST_AT_TIME DECIMAL(10,2) NOT NULL,
    BATCH_ID BIGINT NOT NULL,
    RESOURCE_ID BIGINT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BATCH_ID) REFERENCES tb_batch (ID),
    FOREIGN KEY (RESOURCE_ID) REFERENCES tb_resource (ID)
) ENGINE=InnoDB;

-- ========================================
-- Tabela intermediária: tb_batch_machine_usage
-- ========================================
CREATE TABLE tb_batch_machine_usage (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USAGE_TIME BIGINT NOT NULL,
    BATCH_ID BIGINT NOT NULL,
    MACHINE_ID BIGINT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BATCH_ID) REFERENCES tb_batch (ID),
    FOREIGN KEY (MACHINE_ID) REFERENCES tb_machine (ID)
) ENGINE=InnoDB;
